### ISSUE TITLE
어떻게하면 조금 더 탄력적으로 할 수 있을 것인가

### ISSUE THREAD

**Issue by MagicalLas** [atmosphere-pp/server#8]
진행이 일주일에 PR 0.5개정도가 만들어지는 것 같아 어떻게 하면 조금 더 탄력적으로, 속도를 올릴 수 있을지 고민해보았습니다.

제안: 매주 2회 메일 혹은 다른 방법으로 회고를 진행합니다.

회고와 더 잦은 커뮤니케이션으로 속도를 높이고 잘 가고있는지 확인하는 과정이 있으면 더욱 도움이 될 것 같습니다. 적당히 사적인 이야기와 의도적인 수련들을 같이 이야기 하면 좋을 것 같네요!! 혹시 어떠신가요?

**Comment by wickedev** [comment]
넵 좋습니다. 커뮤니케이션 수단은 어떤걸로 할지 알려주세요. 그럼 즐거운 연말 되시고요 :)

**Comment by MagicalLas** [comment]
메일이 좋을 것 같네요!! 적당히 포멀하고 사생활 문제도 있으니 모두 열람 가능하지 않는게 좋을 것 같다는 생각이 들어서요!!

이번주 수요일날 첫 메일을 작성해보겠습니다!! 매번 새로운 메일 스레드가 만들어질 것 같아요!

**Comment by MagicalLas** [comment]
확실히 속도가 늘었다는걸 체감할 수 있네요. 이 이슈를 연 다음 13일간 6개의 PR이 만들어졌네요.
그 전보다는 훨씬 만족스러운 속도인 것 같습니다.
